package com.tal.pro.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import java.time.LocalDate;

@Data
@Document(collection = "educations")
public class Education {
    @Id
    private String id;
    
    @Field("institution")
    private String institution;
    
    @Field("degree")
    private String degree;
    
    @Field("field_of_study")
    private String fieldOfStudy;
    
    @Field("start_date")
    private LocalDate startDate;
    
    @Field("end_date")
    private LocalDate endDate;
    
    @Field("currently_studying")
    private boolean currentlyStudying;
    
    @Field("description")
    private String description;
    
    @Field("candidate_id")
    private String candidateId;
    
    // Getters and setters are generated by Lombok @Data
}
